### ISSUE TITLE
Loading icons missing

### ISSUE THREAD

**Issue by jwohlfert23** [driftyco/ionicons#111]
loading icons (.ion-loading-a, .ion-loading-b, etc.) are missing from the latest sass and less files

**Comment by bensperry** [comment]
We are working on a new loading spinners pack. They will be significantly better than what was there before. Apologies for the wait... we're almost done and we think you'll love them.

**Comment by marcalj** [comment]
Fantastic! :)

**Comment by bergjs** [comment]
Great! Thanks for the update Ben!

**Comment by kirkstrobeck** [comment]
:+1:

**Comment by sandelius** [comment]
@bensperry Do you have any release date for the new spinners?

**Comment by ozexpert** [comment]
I used font awesome instead..  Works good.

**Comment by bensperry** [comment]
They will be included in the next version of Ionic. Here's a preview: http://ionicframework.com/docs/nightly/api/directive/ionSpinner/

**Comment by kirkstrobeck** [comment]
:+1:

**Comment by marcalj** [comment]
@bensperry Did you plan to pack this **awesome directive** standalone? I'm using ionicons with Twitter Bootstrap on private admin dashboard, not with ionic framework. Can't wait! :dancer: 

Thanks!

**Comment by anthonator** [comment]
Any update on this? I'm kind of baffled this was removed without a replacement. I think a deprecation would have been more appropriate.

![post-28553-steve-jobs-mind-blown-gif-hd-t-pvbd](https://cloud.githubusercontent.com/assets/420061/6205914/c64a23de-b54c-11e4-93d2-1ac7edc564fb.gif)

**Comment by kirkstrobeck** [comment]
and the point of that comment was .. ?

**Comment by jamm** [comment]
had to include whole fontawesome just for spinner :(
Waiting for your spinners.

**Comment by mwawrusch** [comment]
-1

**Comment by toddhalfpenny** [comment]
ion-spinners are available now.
I have a quick post on replacing an old icon with an ion-spinner
http://bit.ly/ionic_spinners_rc0

**Comment by bensperry** [comment]
That's right, with the release of RC 1.0 our new svg spinners are now out! :)

http://ionicframework.com/docs/api/directive/ionSpinner/

**Comment by jamm** [comment]
so now we can't have spinning icons without whole ionic framework in dependencies? it was possible with Ionicons 1.5.

**Comment by perrygovier** [comment]
You can, the icons are still there, we just took out the rotation CSS to keep things lean. The trouble is you'll get a "wobble" with some devices. It's a case where if you fix it for some, you break it for others. The only real way to get animations that have no chance of wobbling is to not us rotating font icons. If you're ok with some wobbling, you can certainly add the CSS back in. The icons themselves still exist. 


Here's an example http://codepen.io/jabranr/pen/GLFjv?editors=110

**Comment by jamm** [comment]
each tab with new spinners use 64% of CPU in Chrome 41.0.2272.74 beta (64-bit), MBPr late 2013.

@perrygovier thanks for example, but I don't see in this example, how I can use directives with just CSS file and without any JS. But will just try...

**Comment by perrygovier** [comment]
Here's another example: http://codepen.io/perrygovier/pen/dPqXyE?editors=110

**Comment by jamm** [comment]
@perrygovier thank you! I'll copy-paste it and will just add "spin" css class to all elements I want to spin (and with price of wobbling, I see). 
Thank you!

**Comment by mixersoft** [comment]
manually added a line to load animations until the new version is ready

    // file ionicons.scss
    @import "ionicons-font";
    @import "ionicons-icons";
    @import "ionicons-animation";  // load animations to use ion-loading-b

**Comment by rahulgit** [comment]
Guys try <ion-spinner icon="crescent" class="spinner-royal"></ion-spinner> 

They invent a new method for spinners :)

**Comment by timlind** [comment]
ion-spinner cannot be used in place of placeholder-icon ... any suggestion?

**Comment by jneubrand** [comment]
@timlind ion-spinner doesn't exist anymore.

**Comment by deba9090** [comment]
Thanks Perrygovier. After using this link, all ion-ios icons are working
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
