### ISSUE TITLE
Request: Beaker icon

### ISSUE THREAD

**Issue by dvorapa** [driftyco/ionicons#154]
![First](http://ecx.images-amazon.com/images/I/41Eq8AF6DgL.jpg)

![Second](http://www.clker.com/cliparts/Q/y/O/d/F/C/green-beaker-md.png)

![Third](http://www.thepartycupboard.com.au/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/6/16060_1.jpg)

**Comment by dvorapa** [comment]
@chuglydude of course you could make it, if you want

**Comment by austinpray** [comment]
This can be closed, there is now a proper beaker icon: https://github.com/driftyco/ionicons/commit/5b7e2fce4d2b6bddf29086eecd3e418bb0cdabb5

**Comment by dvorapa** [comment]
right

**Comment by austinpray** [comment]
:sunglasses: :sunglasses: :sunglasses: :sunglasses:
