### ISSUE TITLE
Please stop including copied icons from PixelLove

### ISSUE THREAD

**Issue by JamesHourd** [driftyco/ionicons#157]
Please don’t copy PixelLove’s work and then pass it off as your own. Many designers work tirelessly producing resources for developers to use in their projects. Sometimes this is offered for free and sometimes for a fair price to cover costs and pay the bills. Myself, I do both.

Many icon sets include generic icons, and as such there will always be similarities between certain sets, especially when they use the same visual language such as the iOS thin icon style. However, the Ionicons icon set replicates a number of PixelLove’s iOS icons, many of which are unique and not found elsewhere. The number of replicated icons both unique and generic makes the possibility of coincidence impossible. Please respect the intellectual property of other people’s work and cease using them without prior permission or without an agreement based on attribution.

I have attached just a few of those that have been replicated. Please be aware that minor tweaks to an icon (mirroring for example) does not constitute a change of ownership of the icons intellectual property.

Many thanks,

James Hourd (PixelLove icons)

![pixelloveicons](https://cloud.githubusercontent.com/assets/9723391/5032517/5000deba-6b56-11e4-90f1-d3a33fe0e0e1.gif)

**Comment by chuglydude** [comment]
No problem it wasn't me
