### ISSUE TITLE
SVG sprite

### ISSUE THREAD

**Issue by oskarrough** [driftyco/ionicons#168]
Hi, thank you for all these fine icons.

Are you considering adding a SVG sprite as alternative to the icon font? There are quite a few [advantages](http://css-tricks.com/icon-fonts-vs-svg/). Partnering up with [Fontastic](http://fontastic.me) could also be an option as it would allow us to pick and choose only the icons we need.

**Comment by tlkiong** [comment]
Its been almost 2 years now. Is there still no SVG support for ionicons?
