### ISSUE TITLE
Request: Floppy Disc Icon

### ISSUE THREAD

**Issue by DannyVickers** [driftyco/ionicons#175]
The Icon Font is very extensive, although I feel it lacks in some specific UI areas, one that is missing but used in other Icon Fonts is a "Floppy Disc" icon, to symbolize a "Save" action, I feel this would be very useful and should definitely be added to the next version, I hope this will be considered, thanks!

**Comment by mnpenner** [comment]
:+1: for floppy disk. We need *something*. I guess I'll use a checkmark for now.

**Comment by bensperry** [comment]
Yeah, I think it's best to move off using that icon going forward. My younger siblings have no idea what it means, and that population is only going to grow.

**Comment by rblakeley** [comment]
When I or someone has time, it would be nice to add "save" tags to the check icons.

**Comment by bensperry** [comment]
Good idea. Will definitely do that.
