### ISSUE TITLE
Some 2.0.0 icons not working as escaped html

### ISSUE THREAD

**Issue by jgberg** [driftyco/ionicons#179]
I have found that both
```
ion-ios-volume-low  with escaped html of &#xf4cf; 
ion-ios-volume-high with escaped html of &#xf3ce;
```
do not work properly when the escaped html is inserted directly into html.  While on the other hand
```
&#xf257;  ion-volume-high
&#xf25a;  ion-volume-mute
```
do work. Also some of the volume items of the genre ion-android-volume.* also fail when used this way. 

These work perfectly under 1.5.2 but not under 2.0.0.   Moreover, it seems that most though not all of the ion-android and the ion-ios icons fail to display when used as direct escaped html now.  In my case, these all work perfectly on 1.5.2.

**Comment by stoplion** [comment]
Having same issue

**Comment by jgberg** [comment]
I think the problem was in our use, not in the icon implementation ... Seek
harder :)
