### ISSUE TITLE
Linux encoding issue

### ISSUE THREAD

**Issue by baldaman** [driftyco/ionicons#183]
Hi, i have a trouble with the python script to the compiling of the new svg icon in os Linux. I had an ascii error about UTF8 encoding and i have a solution that work for me. I leave the change that i made.

-> Added encoding utf8 to org_name and ion_name in line 45 in generate.py script:
svg_text = svg_text.replace(org_name.encode('utf-8'), ion_name.encode('utf-8'))

-> Added "shel=True" parameter to subprocess call in line 152 in generate_font.py script
subprocess.call(['sfnt2woff', fontfile + '.ttf'], shell=True)

With this 2 changes, i cant get the project works. I leave here to help others like me.

Sorry my bad english. Cheers!

**Comment by adamdbradley** [comment]
thanks
