### ISSUE TITLE
ion-android-more-horizontal and ion-android-more-vertical not availble

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionicons#191]
Hey there, I've updated my CLI, created a blank project, but the `ion-android-more-horizontal` and `ion-android-more-vertical` icons are not available even though they appear on ionicons. I would HEART these icons to be available :)

**Comment by bensperry** [comment]
Hey Sean. They are available in the newest version of Ionicons 2.0 (which Ionic currently is not using, but will with RC0). Just make sure you download and update to the latest version and you should be good to go.
