### ISSUE TITLE
ion-ios-pie

### ISSUE THREAD

**Issue by danieljacobarcher** [driftyco/ionicons#192]
The output of including 'ion-ios-pie' or 'ion-ios-pie-outline' do not look the same on the ionicons website. :cry:

**Comment by bensperry** [comment]
Could you give more information? Are you using the [older version](http://ionicons.com/1.5.2/)? We haven't update Ionic to the icons that are currently on the website, so all the id codes have all changed.

**Comment by mlynch** [comment]
Ah, sorry, I ate the pie so your'e just seeing the crusts.

![asdf](http://media.giphy.com/media/BXN5vsT2CDk4g/giphy.gif)

On Mon, Jan 5, 2015 at 1:47 AM, Daniel Jacob Archer <
notifications@github.com> wrote:

> The output of including 'ion-ios-pie' or 'ion-ios-pie-outline' do not look
> the same on the ionicons website. [image: :cry:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionicons/issues/192>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by danieljacobarcher** [comment]
This is on ionicons.com: https://www.dropbox.com/s/vrp2pide9dg8fgc/Screenshot%202015-01-05%2013.33.16.png?dl=0

And when used (installed via bower) it looks like this: https://www.dropbox.com/s/s2aztlk4jsflzon/Screenshot%202015-01-05%2013.33.51.png?dl=0

Seems like the piece of the pie is bigger on ionicons.com (I like the one on the site much better)

**Comment by danieljacobarcher** [comment]
btw using version 2.0 installed via bower

**Comment by bensperry** [comment]
Bower may need to be update... That's definitely the icon from an older version.

**Comment by danieljacobarcher** [comment]
I have no problem with the newer icons though... Anything I can do on my end?

**Comment by danieljacobarcher** [comment]
oh, and I'd downloaded ionicons 2.0 from the ionicons website, and it did have the old version of ion-ios-pie in the src folder.

**Comment by bensperry** [comment]
Weird... taking a look now. Thanks.

**Comment by bensperry** [comment]
Hah! Looks like the website's "download" button is still spitting out the old version. We'll have to fix this... sorry for the confusion.

**Comment by danieljacobarcher** [comment]
That's odd - doesn't explain bower though?

**Comment by bensperry** [comment]
Is this working now?

**Comment by Ionitron** [comment]
Greetings @danieljacobarcher!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
