### ISSUE TITLE
Display icons with the names

### ISSUE THREAD

**Issue by Ehesp** [driftyco/ionicons#193]
Currently I have to scroll through all the icons to find a suitable one. This would be much easier if we could "cmd + f" and text search for common names. 

Font awesome has this, makes it much easier to find suitable icons.

**Comment by dvorapa** [comment]
What about ionicons webpage?

**Comment by bensperry** [comment]
Do you see the searchbar at the top of the page?

**Comment by ceefour** [comment]
:+1: for this.

@bensperry In Android 4.4 browser/Chrome Android I can search for icons but I can't see the name, not after tapping neither holding down works.
