### ISSUE TITLE
Request: gift icon

### ISSUE THREAD

**Issue by ddahan** [driftyco/ionicons#195]
Like the font-awesome one:
http://fortawesome.github.io/Font-Awesome/icon/gift/

**Comment by swapnilmmane** [comment]
Hello Ionic team,

Any update on this icon.

- Regards
Swapnil M Mane

**Comment by roysG** [comment]
any updates?

**Comment by ahmed-abdulmoniem** [comment]
+1

**Comment by joeystandrew** [comment]
Yes please we need this icon. Thanks!

**Comment by srishtilal** [comment]
Much needed pls!

**Comment by jrmeurer** [comment]
+1

**Comment by vctrferreira** [comment]
+1
