### ISSUE TITLE
Icon is not rotating.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [driftyco/ionicons#201]
In 'http://ionicons.com/',  "ion-load-*" was rotating to indicate that those icons can rotate. But now they are not rotating. A month back when i look at the site they are rotating, but not now.

**Comment by marcalj** [comment]
Look at: https://github.com/driftyco/ionicons/issues/111

**Comment by rajeshwarpatlolla** [comment]
Thanks @marcalj. Lets wait for the new loading spinners pack.

**Comment by marcalj** [comment]
:+1:
