### ISSUE TITLE
ios7 icons not updating

### ISSUE THREAD

**Issue by aleesley** [driftyco/ionicons#204]
I had the previous version with ios7 in the icon class names. I updated to the new version and none of the ios icons work. All of the other icons are showing as normal.

**Comment by sahne123** [comment]
Seems the class names were changed from  "ion-ios7-*" to "ion-ios-*". Is there an CSS-File that supoort also the old names?

**Comment by Leezlee** [comment]
my css files and font files were all updated to the most current version with the ion-ios.. naming convention.

**Comment by bensperry** [comment]
The codes for the iOS style icons have changed as well, not just the removal of "7" from the class name. Since some new icons were added to that pack, all them have different codes. Make sure you check ionicons.com and you're using the most up to date code.
