### ISSUE TITLE
404 DNS error 

### ISSUE THREAD

**Issue by EddyF** [driftyco/ionicons#208]
http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
returning 404

**Comment by mlynch** [comment]
it's an issue with MaxCDN right now. They are working on it. It works for
me, btw, so it'll be fixed soon (DNS issues)

On Tue, Feb 3, 2015 at 9:02 AM, Eddy Ferreira <notifications@github.com>
wrote:

> http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
> returning 404
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionicons/issues/208>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by EddyF** [comment]
Ok, nice one Max

**Comment by paulftw** [comment]
CDN still doesn't work, at least from Australia:

```
x:y paul$ wget http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
--2015-02-04 12:18:43--  http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
Resolving code.ionicframework.com... 108.161.187.131
Connecting to code.ionicframework.com|108.161.187.131|:80... ^C
x:y paul$ ping 108.161.187.131
PING 108.161.187.131 (108.161.187.131): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
^C
--- 108.161.187.131 ping statistics ---
6 packets transmitted, 0 packets received, 100.0% packet loss
x:y paul$ ping github.com
PING github.com (192.30.252.130): 56 data bytes
64 bytes from 192.30.252.130: icmp_seq=0 ttl=52 time=581.721 ms
64 bytes from 192.30.252.130: icmp_seq=1 ttl=52 time=843.342 ms
64 bytes from 192.30.252.130: icmp_seq=2 ttl=52 time=780.574 ms
```

**Comment by paulftw** [comment]
Working as expected now. I guess it's safe to mark this issue as resolved.
