### ISSUE TITLE
ion-spin

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionicons#211]
I may be confused because I'm patching beta14 and I had to backtrack a few time, but did you forget to include `@import "ionicons-animations`?

		@import "ionicons-variables";
		/*!
		  Ionicons, v#{$ionicons-version}
		  Created by Ben Sperry for the Ionic Framework, http://ionicons.com/
		  https://twitter.com/benjsperry  https://twitter.com/ionicframework
		  MIT License: https://github.com/driftyco/ionicons

		  Android-style icons originally built by Google’s
		  Material Design Icons: https://github.com/google/material-design-icons
		  used under CC BY http://creativecommons.org/licenses/by/4.0/
		  Modified icons to fit ionicon’s grid from original.
		*/

		@import "ionicons-font";
		@import "ionicons-icons";

**Comment by marcalj** [comment]
See https://github.com/driftyco/ionicons/issues/111
