### ISSUE TITLE
CDN down on chrome b/c ['Access-Control-Allow-Origin' header contains multiple values '*, *']

### ISSUE THREAD

**Issue by hackape** [driftyco/ionicons#225]
I'm using ionicon with CDN.
(link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css")

And out of a sudden I got this error today, saying:
> Font from origin 'http://code.ionicframework.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

A google search reveals that I'm not the only one, other two folks report the same problem exactly today. Links:
https://css-tricks.com/forums/topic/cross-origin-resource-sharing-error/#post-197554
http://forum.ionicframework.com/t/ionic-cdn-broken/18732

So I guess it's something went wrong on your side, hope you know.

**Comment by mlynch** [comment]
Thanks will be fixing soon.

Co-founder, http://drifty.com/




On Sat, Mar 7, 2015 at 7:48 AM -0800, "hackape" <notifications@github.com> wrote:












I'm using ionicon with CDN.





And out of a sudden I got this error today, saying:




Font from origin 'http://code.ionicframework.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.




A google search reveals that I'm not the only one, other two folks report the same problem exactly today. Links:

https://css-tricks.com/forums/topic/cross-origin-resource-sharing-error/#post-197554

http://forum.ionicframework.com/t/ionic-cdn-broken/18732



So I guess it's something went wrong on your side, hope you know.

**Comment by mlynch** [comment]
Fixed. @adamdbradley I removed the edge rule on the .css regex, but I'm curious where the setting is in MaxCDN for setting CORS globally, as that seems like what is happening. With the edge rule MaxCDN was sending two duplicate headers for `Access-Control-Allow-Origin: *`

**Comment by mlynch** [comment]
Ah, you know what? I think it was the additional of the global regex to add it to everything, that would be my guess. Oh well, it works now.
