### ISSUE TITLE
YouTube icon doesn't match official logo shape

### ISSUE THREAD

**Issue by sgarrity** [driftyco/ionicons#233]
This illustration shows the difference in shape between the ionicon youtube logo and the official YouTube logo.

1. aspect ratio of the box differs (both have the same width in this illustration)
2. Shape of 'play' triangle differs

![youtube-sizes](https://cloud.githubusercontent.com/assets/58062/6849013/4fe4632c-d3af-11e4-92b4-76824f479624.png)

**Comment by dallasbpeters** [comment]
Just make one and add it to your build?
