### ISSUE TITLE
Request: Behance Icon

### ISSUE THREAD

**Issue by DannyVickers** [driftyco/ionicons#240]
Hi, I noticed no Behance Icon has been added with the social icons, could this be added soon possibly in the next version? I'm going to have to use SVG icons for my social page for now, rather than being inconsistent having Ionicons for some and an SVG for another. This would be a really beneficial social icon for my use and probably a lot of other, thanks!

**Comment by mnpenner** [comment]
Just a side note, you can use icomoon.io to convert your SVG icons into a font, and combine them with ionicons.
