### ISSUE TITLE
generate.py does not support paths with spaces or special characters

### ISSUE THREAD

**Issue by theship** [driftyco/ionicons#244]
Little hurdle in using your library: the generate.py paths aren't handling path names with spaces and special characters. 

**Steps:**
1. (On osX 10.10.2) Download ionicons to your google drive: '/Users/devuser/Google Drive/icons&stuff'.
2. Follow build instruction "5) Run the build command:

    python ./builder/generate.py"

**Expected:**
Beautiful icons are generated.

**Actual:**
Errno 2:

    fontforge: can't open file '/Users/devuser/Google': [Errno 2] No such file or directory

then...

    Generate CSS From SCSS
    /bin/sh: stuff/ionicons-2.0.1/builder/../scss/ionicons.scss: No such file or directory

**Workaround:**

Move to path without spaces or special characters or edit generate.py file.

**Comment by matthojo** [comment]
+1

**Comment by theship** [comment]
Fix #244 worked for me! Thanks.
