### ISSUE TITLE
Request: Ticket Icon

### ISSUE THREAD

**Issue by DannyVickers** [driftyco/ionicons#246]
A ticket icon would be great, any word on the next version?

**Comment by roblawford** [comment]
+1

**Comment by amaretto4u** [comment]
+1

**Comment by hafael** [comment]
+999

**Comment by manuman94** [comment]
+1

**Comment by tallcoder** [comment]
+1

I see it was closed, was it added in a hidden area that I can't find?

**Comment by fromage9747** [comment]
@tallcoder Nah, just its a duplicate of https://github.com/ionic-team/ionicons/issues/584

**Comment by bensperry** [comment]
Hey everyone, I'm working on a ticket icon for the next release. Stay tuned, and thanks.
