### ISSUE TITLE
Request: xing icon

### ISSUE THREAD

**Issue by lwinterhalder** [driftyco/ionicons#262]
Hey,

we'd like to use your beautiful iconset but we think that a xing icon is missing.
This was also requested last year #114 and we would appreciate it if the icon would exist in your iconset.

xing is a career-network with 14million users in Europe.
https://www.xing.com/

Thanks

**Comment by keimlink** [comment]
You can find more information on XING on [Wikipedia](https://en.wikipedia.org/wiki/XING), it's a very popular business network in Germany, Austria and Switzerland.

I would appreciate it a lot if you could add a XING icon.

**Comment by appinio** [comment]
same here - would be a real deal to add it! Thanks!

**Comment by Night-Illusions** [comment]
Yepp.. pls add Xing icon. Xing is more used than linkedin in Germany, Austria and Switzerland.

**Comment by bensperry** [comment]
This will be in the next version of ionicons (3.0). Stay tuned!

**Comment by keimlink** [comment]
Thanks! :+1:

**Comment by lwinterhalder** [comment]
Depending to this: https://infinitered.github.io/ionicons-version-3-search/ there´s no xing icon in v3. Will this icon be added soon? Thanks!
