### ISSUE TITLE
Hex codes gone on Ionicons.com

### ISSUE THREAD

**Issue by dolphiq-allard** [driftyco/ionicons#280]
Hey guys,

It seems the Hex codes for icons are removed on the Ionicons.com website. I used this feature a lot.
Would be great if this feature could be restored.

Thanks!!

Cheers,
Allard

**Comment by jbrooksuk** [comment]
https://github.com/driftyco/ionicons/commit/862b403fb5f31e801972a5aab4786c74966a39ee#commitcomment-12036922
