### ISSUE TITLE
Request: Add Free Code Camp icon

### ISSUE THREAD

**Issue by QuincyLarson** [driftyco/ionicons#282]
Free Code Camp is a fast growing open source community of people who practice coding by doing pro bono work for nonprofits. Here's our iconographic logo:

https://pbs.twimg.com/profile_images/562385977390272512/AK29YaTf.png

Our community members plan to use Ionic's Free Code Camp icon when building projects that link back to Free Code Camp, such as their portfolios. We would use it internally in our community as well.

**Comment by flota113** [comment]
:+1:

**Comment by Dzheky** [comment]
+1

**Comment by codemonkey4** [comment]
+1

**Comment by codyjhill99** [comment]
+1

**Comment by aspras** [comment]
+1

**Comment by bensperry** [comment]
Hey guys, unfortunately I can't justify adding this to the pack right now, given that Free Code Camp is not a massively recognizable brand (yet!). We're trying to keep ionicons' base file size as small as possible, and keep our social icons limited to bigger brands like Facebook/Twitter/GitHub/etc. We've done a bit of a reduction for 3.0, so this is in line with that change.

Until then, you're more than welcome to use and distribute the svg/png version of the FCC logo, which will work just as well with the Framework. Best of luck!
