### ISSUE TITLE
Adding of VK social icon

### ISSUE THREAD

**Issue by Almaz** [driftyco/ionicons#286]
Hello guys!
I offer you to add an icon of one of most popular social network in the world.
It is vk.com, here is a vector file: http://www.flaticon.com/free-icon/vk-social-network-logo_25684
Thank you.

**Comment by rustemgareev** [comment]
+1 for this request, please

**Comment by eek4ever** [comment]
+1, please

**Comment by lis4ever** [comment]
+1, please, that's what we need

**Comment by filmakarov** [comment]
+1. Also, it would be great to have both russian and international versions of an icon. An international one is provided by topicstarter. Here is the russian one: http://www.flaticon.com/free-icon/vkontakte-logo_3886
Thanks!

**Comment by Stajor** [comment]
+1

**Comment by electrokokos** [comment]
+1, please

**Comment by bensperry** [comment]
@Almaz It will be in ionicons 3.0 (coming out in a month or so). I'm not going to use the Russian "B" version because it's too similar to Bootstrap and could be confusing. Stay tuned for 3.0!

**Comment by meetgerry** [comment]
Is this out already?

**Comment by etranger** [comment]
+1

**Comment by dariusiiii** [comment]
+1

**Comment by Enkil** [comment]
+1

**Comment by pbt39ppc** [comment]
Hi, that would be enough
http://www.flaticon.com/free-icon/vk-social-network-logo_25684
