### ISSUE TITLE
Request: New Google Icon 

### ISSUE THREAD

**Issue by cgathergood** [driftyco/ionicons#309]
Request for the updated google icon to replace 'ion-social-google'. And the correlating google plus icons.

Branding guideline [here](https://developers.google.com/+/branding-guidelines?hl=en#googleplus-icon)

**Comment by rstacruz** [comment]
:+1:

**Comment by cboillat** [comment]
Any chance to see that happen ?

**Comment by WilldelaVega777** [comment]
+1

**Comment by nadeemkhan** [comment]
+1

**Comment by cho-is** [comment]
+1

**Comment by samantasiqueira** [comment]
+1

**Comment by samuelstevens9** [comment]
+G

**Comment by CNK001** [comment]
+1

**Comment by ThinkWired** [comment]
+1

**Comment by LoganArnett** [comment]
+1

**Comment by namzo** [comment]
+1

**Comment by NeilVGD** [comment]
+1

**Comment by cboillat** [comment]
For info new G+ is available here : https://github.com/driftyco/ionicons/tree/3.0

**Comment by CNK001** [comment]
thx!

**Comment by cgathergood** [comment]
Thanks @cboillat!
