### ISSUE TITLE
Request: Gender Icon

### ISSUE THREAD

**Issue by ituhin** [driftyco/ionicons#315]
gender icon could used as a label with a input field

**Comment by FranzSkuffka** [comment]
there is a transgender icon which would fit nicely.

**Comment by bensperry** [comment]
there are both male, female, and transgender icons which should be sufficient for this use case. Thanks!

**Comment by ituhin** [comment]
@bensperry @FranzSkuffka yes there is male and female icon. but not both combined :) 
some may not like to use the transgender icon, i think there should be something like this - eg: https://github.com/FortAwesome/Font-Awesome/issues/1539

**Comment by bensperry** [comment]
I'm putting this on hold for the time being because it's not critical and we're trying to reduce the size of ionicons with 3.0. Thanks!

**Comment by ituhin** [comment]
Sure @bensperry . its not critical. 
Thanks for the good work :+1:

**Comment by FranzSkuffka** [comment]
There is an icon called `ion-transgender`. Go look it up...
