### ISSUE TITLE
ERROR: python ./builder/generate.py sets all icon content to "{ content: ""; }"

### ISSUE THREAD

**Issue by idekterev** [driftyco/ionicons#324]
Using the python generate.py script overwrites the css file and sets ALL the icon CSS content to:
.ion-alert:before { content: ""; }

Before running the generate.py script all icons in the CSS file (css/ionicons.css) had individual content tags:
ion-alert:before { content: "\f101"; }
etc.

No new icons were added. Just cloned from git, and ran "python ./builder/generate.py". 

Sass 3.4.19 (Selective Steve) installed. 
fontforge-20150612 installed
ttfautohint-1.3 installed
Python 2.7.10

**Comment by pikiou** [comment]
I had the same issue.
So I used what was in branch 3.0 and it works there.

**Comment by adamdbradley** [comment]
Is this an issue in the 3.0 branch?

**Comment by Ionitron** [comment]
Greetings @idekterev!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
