### ISSUE TITLE
request: start and end arrows.

### ISSUE THREAD

**Issue by FranzSkuffka** [driftyco/ionicons#325]
Icons for indicating movement to the end of a list.
If this will be merged I can create `android-arrow-end` and `android-arrow-start` svg files.

**Comment by bensperry** [comment]
Can you visually show me examples of these icons from Android's MD icon pack?

**Comment by FranzSkuffka** [comment]
something like this:

http://www.freepik.com/free-icon/navigate-to-end-right-arrow-symbol-with-vertical-bar_723615.htm

**Comment by bensperry** [comment]
Icons like this will be in the next version of ionicons (3.0). Stay tuned!

**Comment by FranzSkuffka** [comment]
For sure!

**Comment by bensperry** [comment]
check the 3.0 branch. the skip-forward and skip-backward icons are what we're going with for this.

**Comment by FranzSkuffka** [comment]
Ok, so I was trying to use this for pagination. As the skip-forward and skip-backward icons look completely different from any other arrow this does not really resolve that issue.

Not pressing at all, but I am sure I am not the only one that will encounter this

**Comment by bensperry** [comment]
It's close enough for this pack. We are trying to reduce the file size of
Ionicons 3.0, so adding the slightly different version is off the table.
Thanks!

On Mon, Jan 11, 2016 at 3:47 PM, Jan Wirth <notifications@github.com> wrote:

> Ok, so I was trying to use this for pagination. As the skip-forward and
> skip-backward icons look completely different from any other arrow this
> does not really resolve that issue.
>
> Not pressing at all, but I am sure I am not the only one that will
> encounter this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionicons/issues/325#issuecomment-170700920>.
>



-- 

*Ben Sperry*

Co-founder, Ionic.


*Twitter* @benjsperry • *Skype* ben.sperry • *Phone* 414.418.4602
