### ISSUE TITLE
is ionicons dead?

### ISSUE THREAD

**Issue by alesrosina** [driftyco/ionicons#326]
Hi guys - is this repo already dead? There was not activity in more than half a year.

I mean the icons are awesome, it would be really bad if it would die ... Do you need any more contributors? I would love to help out.

**Comment by CheetahDev** [comment]
Same question. :+1:

**Comment by stilnick** [comment]
Same question. i love the ionic icons.

**Comment by JerryLopez** [comment]
Would like to know too.

**Comment by JerryLopez** [comment]
@alesrosina @CheetahDev @stilnick Looks like it's not dead they are working on 3.0. Check out that branch and you'll see that they've made recent changes.

**Comment by bensperry** [comment]
@alesrosina No, no dead! We've just been working hard on Ionicons 3.0 (and ionic 2), which will be a big change to how things work. Stay tuned...

**Comment by Stexxen** [comment]
Unfortunately I can see no commits on v3 since mid Jan.... :disappointed:

**Comment by bensperry** [comment]
Oh come on now, we're not dead! 😂 

We've been working on [Ionic Framework v2](http://ionicframework.com/docs/v2/), but my hope is to get ionicons v3 updated and released alongside the stable (RC) release of v2 in the next month or so. Stay tuned!
