### ISSUE TITLE
Request: Group and Ungroup icon and Remove Filter icon (i.e. Funnel with cross)

### ISSUE THREAD

**Issue by hp2ra** [driftyco/ionicons#327]
Requesting for Group and Ungroup icon.
http://fortawesome.github.io/Font-Awesome/icon/object-group/
http://fortawesome.github.io/Font-Awesome/icon/object-ungroup/

There is a funnel for filter, would it be possible to add the Remove Filter icon Funnel with cross mark

**Comment by bensperry** [comment]
I'm not sure this fits within the scope of Ionicons right now. It's too specific/focused on image editing, and I'd recommend using FA or another pack for those types of custom icons!
