### ISSUE TITLE
Request: Info icon and search filter

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionicons#332]
Hello guys!
Great work.

What you think about adding the possibility to filter through the icons by typing their names?
Sometimes it gives an headache to scroll down several times all the icons to look for the one that fit the best for each specific case.

Thank you!

**Comment by bensperry** [comment]
You can use the search bar at the top of the page to do just that.

**Comment by FrancescoMussi** [comment]
Holy cow! 
It works perfectly!
I swear i didn't see it

**Comment by bensperry** [comment]
:+1: !
