### ISSUE TITLE
Incorrect Google+ Icon

### ISSUE THREAD

**Issue by DustinWStout** [driftyco/ionicons#337]
The Google+ icon being used in ionicons is 2 years outdated. The new icon is a capital G+. I have already vectorized myself and would be happy to send it your way if need be. Just let me know where to send it.

**Comment by bensperry** [comment]
Yep, it's already made and included in Ionicons 3.0 which will be dropping sometime within the next month. Stay tuned!

**Comment by DustinWStout** [comment]
Woo-hoo!

On Mon, Jan 11, 2016 at 7:00 AM Ben Sperry <notifications@github.com> wrote:

> Yep, it's already made and included in Ionicons 3.0 which will be dropping
> sometime within the next month. Stay tuned!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionicons/issues/337#issuecomment-170579617>.
>
-- 
*Dustin W. Stout*
*Speaker, Consultant, Coffee-Lover*
dustn.tv
