### ISSUE TITLE
Request: LinkedIn icon without the box

### ISSUE THREAD

**Issue by ThinkWired** [driftyco/ionicons#366]
Please give us just the "in" so we can make our own box and style accordingly (like fontawesome). Maybe just offer a third variation without the box?

**Comment by bensperry** [comment]
Hey @ThinkWired! While I agree it would be nice to have just the 'in" style, I'm simply going off of LinkedIn's terms of logo use, which require the outer box. Unfortunately, there's no room for adding a lot of variations (at least not yet!) as we're trying to keep the overall size of Ionicons as small as we can.

We are working on a potential way to expand the overall size (and thus variations of icons) without sacrificing performance on mobile devices, but it's still in the early stages of that.

**Comment by ThinkWired** [comment]
If that is true then ion-social-linkedin-outline breaks their terms of logo use and should be removed from the collection.

**Comment by bensperry** [comment]
Haha... If there is a concession to be made, that is the only one I'm comfortable with. However, in Ionicons 3.0 we've completely removed the outline version altogether:

http://ionicframework.com/docs/v2/resources/ionicons/

**Comment by ThinkWired** [comment]
I concede and withdraw my original request.

Its funny how this played out. I knew you were going to come back and hit me with guidelines so, I sat in wait so I could hit you with .ion-social-linkedin-outline being outside of the guidelines.

I did not see the "finish him -- fatality" of  ion-social-linkedin-outline already being removed in v3 coming. Kudos to you sir.

Is there a 3.0 release date?

**Comment by bensperry** [comment]
Thanks for that, I lol'd over here!

Technically Ionicons 3.0 is already done, and will be made widely available int he coming weeks. Stay tuned!
