### ISSUE TITLE
Request: History Icon

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionicons#372]
Please add the following icon or something similar that represents history:
![history-128](https://cloud.githubusercontent.com/assets/9930079/14561530/92a59d7a-031f-11e6-8f81-63c154472822.png)

**Comment by ThorConzales** [comment]
Irrelevant.

**Comment by untmat** [comment]
Please reopen this issue, it would be great to have a history icon.

**Comment by hashguide** [comment]
Font Awesome 5 has this history icon and would be nice to have in ionicons!

**Comment by fonsp** [comment]
Moved to https://github.com/ionic-team/ionicons/issues/952
