### ISSUE TITLE
upgrade HTTP to HTTPS

### ISSUE THREAD

**Issue by wesharehoodies** [driftyco/ionicons#440]
Hello, 

Very awesome font icons, I love them. Is there a reason the CDN serves HTTP instead of HTTPS?
- http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css

**Comment by exomarty** [comment]
+1

**Comment by tomsterritt** [comment]
The CDN serves both HTTP and HTTPS: https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
