### ISSUE TITLE
Import ionicons into ionic2 application

### ISSUE THREAD

**Issue by eshk12** [driftyco/ionicons#451]
GitHub Link: [my_repostory](https://github.com/eshk12/Parabi/tree/DB-LINKED/)
I have found Driftyco's ionicons repository, And I would like to use it.

I have download it and import the files `ionicons.css` and folder `fonts` into my folder `/src/assets`, And insert the css file inside `/src/index.html`.

I have also change the `fonts` dir in the css file to the correct location.
When I write this in my code `<i class="icon ion-home"></i>` nothing happen.

It's seem that's not recognized it.

Please help :)

**Comment by royipressburger** [comment]
You dont really need to change fonts, add imports or download manually the ionicons project. 

As you can see ionicons allready present in you package.json

Your problem is that you are not using it right on your html.

`<ion-icon name="home"></ion-icon>`

**Comment by eshk12** [comment]
ohh thx I havent think that's isn't usable any more.

Thanks!
