### ISSUE TITLE
Confused by this project and the icons included in ionic2

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionicons#464]
The icons we see in the new ionic2 documentation are different from this icons, there are less icons and different for any mobile device (md, ios, windows) which is all okay.

But I don't know what is the difference between this project and the other icons. In the ionic2 documentation there is now hint to this icons.

But if I create a new project with the ionic-cli there is a npm package included "ionicons" i version 3.0.0
which should be this npm packge https://www.npmjs.com/package/ionicons
On the page there is the link for the github project which is still this project here!
In this project you link to this page http://ionicons.com/

But there is the problem, the icons included in my ionic2 project are not the same as I can see in your linked page!

So now I'm a little bit confused!

Can we use or can we not use this icons in ionic2 project? Is your readme wrong?
What are the difference between this icons and which are the ideas of the ionic team about the icons?

This is my ionic forum post
https://forum.ionicframework.com/t/difference-from-included-icons-and-http-ionicons-com/79448/4

**Comment by royipressburger** [comment]
This project is the one they use for ionic2. Just not the master branch but 3.0 branch

**Comment by mburger81** [comment]
Yea I saw the 3.0 branch and the included icons which are the one in the ionic2 documenation.
But also in branch 3.0 the readme is talking about the http://ionicons.com where you can see the icons in action, which is completely wrong, so  that confused me.

I think the icon set for 2.0.1 is much better and also there are so many icons we can, the 3.0.0 are also beautiful but we need a lot more of symbols?

Is there a way to include some icons from 2.0.1 in project to use also with <ion-icons> or buttons or something else? We don't need ios icons we need only md icons.

thx

**Comment by perrygovier** [comment]
Ionicons.com has not yet been updated w/ Ionicons v3, which Ionic2 uses. 
You can browse the v3 icons at http://ionicframework.com/docs/v2/ionicons/
